C:\Users\beatr\anaconda3\python.exe C:\Users\beatr\Documents\GitHub\SAFENET-Bea\Modelo.py
2024-09-24 11:14:01.953452: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-09-24 11:14:03.574780: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-09-24 11:14:07.314088: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
Epoch 1/10
    162/Unknown 396s 2s/step - accuracy: 0.4841 - loss: 42.13372024-09-24 11:20:46.274682: I tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
C:\Users\beatr\anaconda3\Lib\contextlib.py:155: UserWarning: Your input ran out of data; interrupting training. Make sure that your dataset or generator can generate at least `steps_per_epoch * epochs` batches. You may need to use the `.repeat()` function when building your dataset.
  self.gen.throw(typ, value, traceback)
2024-09-24 11:21:19.217523: I tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
162/162 ━━━━━━━━━━━━━━━━━━━━ 430s 3s/step - accuracy: 0.4842 - loss: 41.9794 - val_accuracy: 0.6217 - val_loss: 1.9502


Epoch 2/10
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 2s/step - accuracy: 0.5916 - loss: 2.32262024-09-24 11:28:00.064675: I tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
162/162 ━━━━━━━━━━━━━━━━━━━━ 400s 2s/step - accuracy: 0.5915 - loss: 2.3246 - val_accuracy: 0.6822 - val_loss: 1.7444


Epoch 3/10
162/162 ━━━━━━━━━━━━━━━━━━━━ 417s 3s/step - accuracy: 0.6173 - loss: 2.3212 - val_accuracy: 0.6124 - val_loss: 1.9747


Epoch 4/10
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 2s/step - accuracy: 0.5805 - loss: 2.46522024-09-24 11:42:04.159081: I tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
162/162 ━━━━━━━━━━━━━━━━━━━━ 428s 3s/step - accuracy: 0.5805 - loss: 2.4661 - val_accuracy: 0.6217 - val_loss: 1.6973


Epoch 5/10
162/162 ━━━━━━━━━━━━━━━━━━━━ 429s 3s/step - accuracy: 0.6133 - loss: 2.4751 - val_accuracy: 0.6295 - val_loss: 1.7420


Epoch 6/10
162/162 ━━━━━━━━━━━━━━━━━━━━ 414s 3s/step - accuracy: 0.6128 - loss: 2.1746 - val_accuracy: 0.6186 - val_loss: 1.7792


Epoch 7/10
162/162 ━━━━━━━━━━━━━━━━━━━━ 415s 3s/step - accuracy: 0.6212 - loss: 2.2117 - val_accuracy: 0.6202 - val_loss: 1.6264


Epoch 8/10
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 2s/step - accuracy: 0.6134 - loss: 2.05052024-09-24 12:09:53.365176: I tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
162/162 ━━━━━━━━━━━━━━━━━━━━ 411s 3s/step - accuracy: 0.6134 - loss: 2.0515 - val_accuracy: 0.6155 - val_loss: 1.7881


Epoch 9/10
162/162 ━━━━━━━━━━━━━━━━━━━━ 405s 3s/step - accuracy: 0.6101 - loss: 2.1436 - val_accuracy: 0.6140 - val_loss: 1.6467


Epoch 10/10
162/162 ━━━━━━━━━━━━━━━━━━━━ 431s 3s/step - accuracy: 0.6099 - loss: 2.0671 - val_accuracy: 0.6140 - val_loss: 1.6128



Epoch 1/10
162/162 ━━━━━━━━━━━━━━━━━━━━ 518s 3s/step - accuracy: 0.6050 - loss: 1.9914 - val_accuracy: 0.6186 - val_loss: 1.6157


Epoch 2/10
162/162 ━━━━━━━━━━━━━━━━━━━━ 508s 3s/step - accuracy: 0.6072 - loss: 1.9298 - val_accuracy: 0.6186 - val_loss: 1.5796


Epoch 3/10
162/162 ━━━━━━━━━━━━━━━━━━━━ 565s 3s/step - accuracy: 0.6053 - loss: 1.9381 - val_accuracy: 0.6171 - val_loss: 1.5743


Epoch 4/10
162/162 ━━━━━━━━━━━━━━━━━━━━ 551s 3s/step - accuracy: 0.6077 - loss: 1.9227 - val_accuracy: 0.6171 - val_loss: 1.5440


Epoch 5/10
162/162 ━━━━━━━━━━━━━━━━━━━━ 548s 3s/step - accuracy: 0.6063 - loss: 1.9486 - val_accuracy: 0.6171 - val_loss: 1.5299


Epoch 6/10
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 3s/step - accuracy: 0.6117 - loss: 1.88132024-09-24 13:17:46.474668: I tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
162/162 ━━━━━━━━━━━━━━━━━━━━ 547s 3s/step - accuracy: 0.6116 - loss: 1.8817 - val_accuracy: 0.6186 - val_loss: 1.5179


Epoch 7/10
162/162 ━━━━━━━━━━━━━━━━━━━━ 546s 3s/step - accuracy: 0.6046 - loss: 1.8377 - val_accuracy: 0.6186 - val_loss: 1.4778


Epoch 8/10
162/162 ━━━━━━━━━━━━━━━━━━━━ 547s 3s/step - accuracy: 0.6056 - loss: 1.7860 - val_accuracy: 0.6186 - val_loss: 1.4586


Epoch 9/10
162/162 ━━━━━━━━━━━━━━━━━━━━ 539s 3s/step - accuracy: 0.6058 - loss: 1.7095 - val_accuracy: 0.6186 - val_loss: 1.4564


Epoch 10/10
162/162 ━━━━━━━━━━━━━━━━━━━━ 542s 3s/step - accuracy: 0.6115 - loss: 1.6435 - val_accuracy: 0.6186 - val_loss: 1.4535


21/21 ━━━━━━━━━━━━━━━━━━━━ 35s 2s/step - accuracy: 0.6082 - loss: 1.4517

Test Loss: 1.4855977296829224
Test Accuracy: 0.6012364625930786

Process finished with exit code 0